animations = [
    { 
        name = "standing",
        directions = ["side", "front", "back"],
        frames = [1, 1, 1]
    },
    { 
        name = "walking",
        directions = ["side", "front", "back"],
        frames = [8, 8, 8]
    },
    { 
        name = "melee_slash",
        directions = ["side", "front", "back"],
        frames = [6, 6, 6]
    },
    { 
        name = "dead",
        directions = ["side", "front", "back"],
        frames = [1, 1, 1]
    },
]

pack = "orc.pack"
