[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
  spatial = {x = 300.0, y = 100.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
  spatial = {x = 920.0, y = 100.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
  spatial = {x = 100.0, y = 200.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
  spatial = {x = 100.0, y = 500.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
  spatial = {x = 700.0, y = 20.0, radius = 14.0, direction = "west"}
}

[[free-item]]
template = "sword"
comp_overrides = ["spatial", "eqweapon"]
components = {
  spatial = { x = 180.0, y = 180.0, radius = 10.0},
  eqweapon = { type = "sword", baseDamage = 25, size = 4}
}

[[container]]
[[trigger]]
[[npc]]
