[[mob]]
components = {
    Spatial = {x = 300.0, y = 100.0, radius = 14.0, direction = '''West'''},
    State = {current = '''Standing'''},
    AnimatedRenderable = { animDir = '''./mob/orc/''' },
    Martial = {},
    Equipment = {},
    Inventory = {},
    MobAI = { state = '''Wander''' },
    Attribute = {}
}
inventory = []
equipment = {
    Held = {
        Spatial = {pos = '''Carried'''},
        Renderable = {textureSource = '''./items/steel-sword.png'''},
        Item = {name = '''A short sword''', description = '''This short sword is dull'''},
        EqItem = {hr = 1, slot = '''Held'''},
        EqWeapon = { weaponClass = '''Sword''', baseDamage = 5, size = 4.0}
    }
}

[[mob]]
components = {
    Spatial = {x = 920.0, y = 100.0, radius = 14.0, direction = '''West'''},
    State = {current = '''Standing'''},
    AnimatedRenderable = { animDir = '''./mob/orc/''' },
    Martial = {},
    Equipment = {},
    Inventory = {},
    MobAI = { state = '''Wander''' },
    Attribute = {}

}
inventory = []
equipment = {}

[[mob]]
components = {
    Spatial = {x = 100.0, y = 200.0, radius = 14.0, direction = '''West'''},
    State = {current = '''Standing'''},
    AnimatedRenderable = { animDir = '''./mob/orc/''' },
    Martial = {},
    Equipment = {},
    Inventory = {},
    MobAI = { state = '''Wander''' },
    Attribute = {}

}
inventory = []
equipment = {}

[[mob]]
components = {
    Spatial = {x = 100.0, y = 500.0, radius = 14.0, direction = '''West'''},
    State = {current = '''Standing'''},
    AnimatedRenderable = { animDir = '''./mob/orc/''' },
    Martial = {},
    Equipment = {},
    Inventory = {},
    MobAI = { state = '''Wander''' },
    Attribute = {}

}
inventory = []
equipment = {}

[[mob]]
components = {
    Spatial = {x = 700.0, y = 20.0, radius = 14.0, direction = '''West'''},
    State = {current = '''Standing'''},
    AnimatedRenderable = { animDir = '''./mob/orc/''' },
    Martial = {},
    Equipment = {},
    Inventory = {},
    MobAI = { state = '''Wander''' },
    Attribute = {}

}
inventory = []
equipment = {}

[[free-item]]
components = {
    Spatial = {x = 180.0, y = 180.0, radius = 16.0},
    Renderable = {textureSource = '''./items/steel-sword.png'''},
    Item = {name = '''A short sword''', description = '''This short sword is dull'''},
    EqItem = {hr = 1, slot = '''Held'''},
    EqWeapon = { weaponClass = '''Sword''', baseDamage = 5, size = 4.0}
}

[[container]]
[[trigger]]
[[npc]]
