[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
    spatial = {x = 300.0, y = 100.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
    spatial = {x = 920.0, y = 100.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
    spatial = {x = 100.0, y = 200.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
    spatial = {x = 100.0, y = 500.0, radius = 14.0, direction = "west"}
}

[[mob]]
template = "orc"
inventory = []
equipment = {}
comp_overrides = ["spatial"]
components = {
    spatial = {x = 700.0, y = 20.0, radius = 14.0, direction = "west"}
}

[[free-item]]
components = {
    Spatial = {x = 180.0, y = 180.0, radius = 16.0},
    Renderable = {textureSource = "./items/steel-sword.png"},
    Item = {name = "A short sword", description = "This short sword is dull"},
    EqItem = {hr = 1, slot = "held"},
    EqWeapon = { type = "sword", baseDamage = 5, size = 4.0}
}

[[container]]
[[trigger]]
[[npc]]
